### ISSUE TITLE
PayPal Express addon stripping option value

### ISSUE THREAD

**Issue by LinuxJedi** [arastta/addons#21]
In four places in the code this is used:

```php
$option['option_value']
```

Whereas getProducts is actually supplying:

```php
$option['value']
```

The PayPal Express addon's version of this variable is what is stored in the final order details which means it is impossible to tell what option was selected without doing DB several queries by hand.

**Comment by LinuxJedi** [comment]
I can supply a patch for this but I'm about to shoot of to work in Moscow for a week so it won't be for a week or so.

**Comment by cuneytsenturk** [comment]
Thanks Andrew,
